#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgname=eigen
  pkgver=${VERSION:-3.4.0}
  pkgfull=${pkgname}-${pkgver}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://gitlab.com/libeigen/eigen/-/archive/${pkgver}/${pkgfn}

  download_md5 $pkgfn $pkgurl 4c527a9171d71a72a9d4186e65bea559

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgname=eigen
  pkgbranch=${VERSION:-master}
  pkgfull=${pkgname}-${pkgbranch}

  # unpack (clone)
  syncgit https://github.com/pybind ${pkgname} ${pkgbranch} ${pkgfull}

else

  devenv_display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

if [ "${DEVENV_DLONLY}" == "1" ] ; then
  echo "\${DEVENV_DLONLY}=1 ; existing"
  exit 1
else
  echo "if you want to exit after downloading: export \${DEVENV_DLONLY}=1"
fi

# build.

# prepare files for building.
#if [ ! -e ${DEVENVPREFIX}/bin/python3 ]; then
#  devenv_display -e "Python3 not exist!!"
#  exit
#fi

#PYTHON=${DEVENVPREFIX}/bin/python3

cmakecmd=("cmake")
cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")

if [ -z "${CMAKE_BUILD_TYPE}" ] ; then
  CMAKE_BUILD_TYPE=Release
  if [[ $DEVENVFLAVOR == dbg* ]] ; then
    CMAKE_BUILD_TYPE=Debug
  fi
fi
cmakecmd+=("-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
#cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")

mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build > /dev/null

  buildcmd cmake.log "${cmakecmd[@]}" ..
  buildcmd make.log make -j $NP
  buildcmd install.log make install

  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null
    buildcmd build/setup.log $PYTHON setup.py install
  popd > /dev/null

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
