#!/usr/bin/env bash

set -e

pkgname=libffi
pkgver=${VERSION:-3.5.1}
pkgfull=$pkgname-$pkgver
pkgfn=$pkgfull.tar.gz
pkgmd5=a67b82e7ec069f15cd81c23ced5049f4
pkgsha512=3da9e21fdb920e7962ceb01ee671ef36196df4d5dad62e0cdd8e87cc60e350f241c204350560ae26ea04cc898161b5585c8a5a5125bdbcc84508efbb7ea61eb8
pkgurl=https://src.fedoraproject.org/repo/pkgs/libffi/${pkgfn}/sha512/${pkgsha512}/${pkgfn}

download_md5 $pkgfn $pkgurl $pkgmd5

mkdir -p ${DEVENVCURRENTROOT}/src
pushd ${DEVENVCURRENTROOT}/src > /dev/null
  tar xf ${DEVENVDLROOT}/$pkgfn
popd > /dev/null

cfgcmd=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVCURRENTROOT}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
